import { library } from '@fortawesome/fontawesome-svg-core'
import { faKeyboard } from '@fortawesome/free-regular-svg-icons'
import {
  faBookReader,
  faEnvelope,
  faVolumeMute,
  faVolumeUp,
  faEye,
  faEyeSlash,
  faAssistiveListeningSystems,
  faCoffee,
  faMicrophone,
  faMicrophoneSlash,
  faMoon,
  faSun,
  faCheckCircle,
  faTerminal,
  faExclamation,
  faRandom,
  faRepeat,
  faRotate,
  faCircleCheck,
  faCheck,
  faTriangleExclamation,
  faHeart,
  faThumbsUp,
  faTimes,
  faTimesCircle,
  faEarthAmericas,
} from '@fortawesome/free-solid-svg-icons'
import { faGithub, faWeixin } from '@fortawesome/free-brands-svg-icons'

library.add(
  faKeyboard,
  faBookReader,
  faGithub,
  faWeixin,
  faEnvelope,
  faVolumeUp,
  faVolumeMute,
  faEye,
  faEyeSlash,
  faAssistiveListeningSystems,
  faCoffee,
  faMicrophone,
  faMicrophoneSlash,
  faMoon,
  faSun,
  faCheckCircle,
  faTerminal,
  faExclamation,
  faRandom,
  faRepeat,
  faRotate,
  faCircleCheck,
  faCheck,
  faTriangleExclamation,
  faHeart,
  faThumbsUp,
  faTimes,
  faTimesCircle,
  faEarthAmericas,
)
